Roboshop

diff --git a/Mongodb b/Mongodb
--- a/Mongodb
+++ b/Mongodb
@@ -26,9 +26,27 @@ fi
 VALIDATE(){
     if [ $1 -eq 0 ]
     then
-        echo -e "Installing $2 is ... $G SUCCESS $N" | tee -a $LOG_FILE
+        echo -e "$2 is ... $G SUCCESS $N" | tee -a $LOG_FILE
     else 
-        echo -e "Installing $2 is ... $G FAILURE $N" | tee -a $LOG_FILE
+        echo -e "$2 is ... $G FAILURE $N" | tee -a $LOG_FILE
         exit 1
     fi
 }
+
+cp mongo.repo /etc/yum.repos.d/mongo.repo
+VALIDATE $? "copying mongo.repo"
+
+dnf install mongodb-org -y  &>>$LOG_FILE
+VALIDATE $? "Installing mongodb server"
+
+systemctl enable mongod &>>$LOG_FILE
+VALIDATE $? "enabling mongodb"
+
+systemctl start mongod &>>$LOG_FILE
+VALIDATE $? "starting mongodb"
+
+sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mongod.conf
+VALIDATE $? "Editing Mongodb conf file for remote connections"
+
+systemctl restart mongod &>>$LOG_FILE
+VALIDATE $? "Restarting Mongodb"
