frontend

diff --git a/shipping b/shipping
--- a/shipping
+++ b/shipping
@@ -28,15 +28,15 @@ echo "please enter root password to setup"
 read -s MYSQL_ROOT_PASSWORD
 
 # validate functions takes input as exit status, what command they tried to install
-VALIDATE(){
-if [ "$1" -eq 0 ]
-    then
-        echo -e "$2 is ... $G SUCCESS $N" | tee -a $LOG_FILE
-    else 
-        echo -e "$2 is ... $G FAILURE $N" | tee -a $LOG_FILE
-        exit 1
-    fi
+VALIDATE() {
+  if [ "$1" -eq 0 ]; then
+    echo -e "$2 is ... ${G}SUCCESS${N}" | tee -a "$LOG_FILE"
+  else 
+    echo -e "$2 is ... ${G}FAILURE${N}" | tee -a "$LOG_FILE"
+    exit 1
+  fi
 }
+
 
 dnf install maven -y &>>$LOG_FILE
 VALIDATE $? "installing maven and java"
